name: qt
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=2.0.5
  - backcall=0.2.0
  - bcrypt=4.2.0
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - ca-certificates=2025.11.4
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.1
  - contourpy=1.0.5
  - cryptography=43.0.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=0.8.3
  - fonttools=4.51.0
  - freetype=2.12.1
  - h5py=3.11.0
  - hdf5=1.12.1
  - icc_rt=2022.1.0
  - icu=58.2
  - idna=3.7
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - ipykernel=6.28.0
  - ipython=8.12.2
  - jedi=0.19.1
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libusb=1.0.27
  - libwebp-base=1.3.2
  - llvmlite=0.41.0
  - lz4-c=1.9.4
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - nest-asyncio=1.6.0
  - numba=0.58.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openjpeg=2.4.0
  - openssl=3.3.1
  - packaging=24.1
  - pandas=2.0.3
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.0
  - platformdirs=3.10.0
  - plumbum=1.9.0
  - ply=3.11
  - pooch=1.7.0
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.22
  - pygments=2.15.1
  - pylablib=1.4.3
  - pynacl=1.5.0
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtgraph=0.13.1
  - pyserial=3.5
  - pysocks=1.7.1
  - python=3.8.19
  - python-dateutil=2.9.0post0
  - python-tzdata=2024.1
  - python_abi=3.8
  - pytz=2024.1
  - pyusb=1.2.1
  - pyvisa=1.14.1
  - pywin32=305
  - pywin32-on-windows=0.1.0
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - requests=2.32.3
  - rpyc=5.3.0
  - scipy=1.10.1
  - setuptools=69.5.1
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tomli=2.0.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.11.0
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - vc=14.2
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.5
  - wheel=0.43.0
  - win_inet_pton=1.1.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - cffi==1.16.0
      - enum-compat==0.0.3
      - future==1.0.0
      - imagingcontrol4==1.2.0.2954
      - iso8601==2.1.0
      - newportxps==0.3.0
      - opencv-python==4.10.0.84
      - paramiko==3.4.0
      - pysftp==0.2.9
      - pyueye==4.96.952
      - pyyaml==6.0.1
      - serial==0.0.97

