name: acquisition
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - asttokens=3.0.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - cairo=1.18.4=he9e932c_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py312h214f63a_0
  - cpython=3.12.12=py312hd8ed1ab_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.8.17=py312ha1a9051_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h885b0b7_3
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py312h02ab6af_0
  - freetype=2.13.3=h0620614_0
  - graphite2=1.3.14=hd77b12b_1
  - h5py=3.15.1=py312he283ef2_0
  - harfbuzz=10.2.0=he2f9f60_1
  - hdf5=1.14.5=ha36df97_2
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=7.1.0=pyh6dadd2b_0
  - ipython=9.8.0=pyhe2676ad_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jpeg=9f=ha349fce_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyh6dadd2b_0
  - kiwisolver=1.4.9=py312h03f52e7_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libdeflate=1.17=h2bbff1b_1
  - libexpat=2.7.3=h885b0b7_3
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libsodium=1.0.20=hc70643c_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.6.0=hbf3958f_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib=3.10.6=py312haa95532_1
  - matplotlib-base=3.10.6=py312h43afe63_1
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py312h0b37514_0
  - mkl_fft=2.1.1=py312h300f80d_0
  - mkl_random=1.3.0=py312ha5e6156_0
  - mpi=1.0=msmpi
  - mpi4py=4.0.3=py312h827c3e9_0
  - msmpi=10.1.1=had4844c_0
  - msys2-conda-epoch=20160418=1
  - mysql-common=9.3.0=hc394544_4
  - mysql-libs=9.3.0=h58c8544_4
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.3.5=py312h050da96_0
  - numpy-base=2.3.5=py312h1e017a8_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.6.0=h725018a_0
  - packaging=25.0=py312haa95532_1
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=h5740b90_0
  - pillow=11.1.0=py312h096bfcc_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py312he5662c2_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.5=py312haa95532_0
  - pyqt=6.9.1=py312h12ec796_0
  - pyqt6-sip=13.10.2=py312h630b2a1_0
  - python=3.12.12=h716150d_1
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-gil=3.12.12=hd8ed1ab_1
  - python_abi=3.12=3_cp312
  - pywin32=311=py312h829343e_1
  - pyzmq=27.1.0=py312hbb5da91_0
  - qtbase=6.9.2=h06bae2a_5
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - setuptools=80.9.0=py312haa95532_0
  - sip=6.12.0=py312h706e071_0
  - six=1.17.0=py312haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tk=8.6.15=hf199647_0
  - tornado=6.5.1=py312h827c3e9_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py312haa95532_0
  - xz=5.6.4=h4754444_1
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhcf101f3_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - enum-compat==0.0.3
      - imagingcontrol4==1.4.0.3240
      - llvmlite==0.45.1
      - numba==0.62.1
      - pandas==2.3.3
      - plumbum==1.10.0
      - pyft232==0.12
      - pylablib==1.4.4
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.2
      - pyqtgraph==0.14.0
      - pyserial==3.5
      - pytz==2025.2
      - pyueye==4.96.952
      - pyusb==1.3.1
      - pyvcam==2.3.1
      - pyvisa==1.15.0
      - rpyc==6.0.2
      - scipy==1.16.3
      - tzdata==2025.2
prefix: D:\miniconda\envs\acquisition
